### ISSUE TITLE
PBI - Leitura e marcação de arquivo

### ISSUE THREAD

**Issue by ceduardoferreira** [gepetojj/shelf#2]
# Descrição
- Fazer a exibição dos arquivos de forma que o usuário possa ler o conteúdo e fazer marcações (grifar e comentar uma seleção de texto).

# Due date
- 10/06/2024

# História de Usuário
- Eu, como usuário, gostaria de fazer a leitura dos arquivos disponíveis no Shelf (meus e de outras pessoas) e poder selecionar partes do conteúdo para fazer marcação com cores (grifar) e comentar. 

# Tasks
- [x] Exibir o conteúdo para o usuário
- [x] Permitir a seleção e marcação
- [x] Permitir que o usuário avance mais de uma página
- [x] Disponibilizar chatbot de IA (ou pelo menos o espaço)

**Comment by gepetojj** [comment]
finalizado no commit 2d24853
> seleção e marcação já estão disponíveis internamente, mas ainda não para o usuário. nos próximos commits isso já será possível
